### ISSUE TITLE
question for uart print output

### ISSUE THREAD

**Issue by davesliu** [beckus/stm32_p103_demos#10]
hello

The demo code can be run, but it seems that uart output info are not showm in the console.
How to fix it? 
thanks

**Comment by beckus** [comment]
@davesliu Sorry for the long delay. Did you figure this out?
You need to use one of the make targets that sets up a PTY device or telnet server, and then connect using an appropriate terminal program. It's mentioned in the README under "Running in QEMU".

**Comment by davesliu** [comment]
I didnot try it. Thanks anyway
