### ISSUE TITLE
CRLF handling in each source file

### ISSUE THREAD

**Issue by jserv** [beckus/stm32_p103_demos#2]
At present, the source tree contains mixed CRLF-ending lines, that is quite unfriendly to UNIX users.

Using the text attribute in the `.gitattributes` might help, but I would wish the converting to UNIX style ending lines.

**Comment by beckus** [comment]
I agree.  I had not been paying attention to how many CRLF endings were in the project.  I will add it to my to-do list.

**Comment by beckus** [comment]
I removed all carriage returns using the following commands:
To identify files with carriage returns (the ^M is created by typing Ctrl-v and then Ctrl-m):
find . -print0 | xargs -0 grep -l '^M$'

To remove carriage returns (I got this command from the forum post http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git):
find . -type f -not -path "./.git/*" -exec dos2unix {} \;

I also created a .gitattributes file to prevent future issues.
