### ISSUE TITLE
How to emulate a button press in the `button` demo?

### ISSUE THREAD

**Issue by exebook** [beckus/stm32_p103_demos#8]
I can see LED "blinking" but how to emulate a button press?

**Comment by lcgamboa** [comment]
Take a look at:
https://github.com/beckus/qemu_stm32/blob/96ba2f18bab98240f8af0a88010f31dfecf8322a/hw/arm/stm32_f103c8.c#L79

**Comment by beckus** [comment]
Thank you for the response @lcgamboa.
